configure: Add check for Python dateutil module
Starting pipbot from an environment without dateutil causes an
ImportError:

    $ pipbot
    Traceback (most recent call last):
      File "/home/chris/.local/bin/pipbot", line 11, in <module>
        import dateutil.relativedelta
    ImportError: No module named dateutil.relativedelta

This patches causes configure to fail if an informative error:

    $ ./configure --enable-tools

    --- >8 snip ---

    checking for python dateutil module... no
    configure: error: Required Python module 'dateutil' is not found